/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fanzhang_sortTest_MainActivity */

#ifndef _Included_com_fanzhang_sortTest_MainActivity
#define _Included_com_fanzhang_sortTest_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fanzhang_sortTest_MainActivity
 * Method:    insertSortC
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_fanzhang_sortTest_MainActivity_insertSortC
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
