/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fanzhang_guolu_MainActivity */

#ifndef _Included_com_fanzhang_guolu_MainActivity
#define _Included_com_fanzhang_guolu_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fanzhang_guolu_MainActivity
 * Method:    startMonitorFromC
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fanzhang_guolu_MainActivity_startMonitorFromC
  (JNIEnv *, jobject);

/*
 * Class:     com_fanzhang_guolu_MainActivity
 * Method:    stopMonitorFromC
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fanzhang_guolu_MainActivity_stopMonitorFromC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
