/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fanzhang_cLogin_MainActivity */

#ifndef _Included_com_fanzhang_cLogin_MainActivity
#define _Included_com_fanzhang_cLogin_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fanzhang_cLogin_MainActivity
 * Method:    checkLogin
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_fanzhang_cLogin_MainActivity_checkLogin
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
